### ISSUE TITLE
Code that worked with 0.3.0 now throws runtime exceptions

### ISSUE THREAD

**Issue by nathan-alden-sr** [Masonry/Masonry#43]
My use case is pretty simple: call `mas_makeConstraints:` on some views. I do this in several places and everything worked perfectly with 0.3.0. As soon as I updated to 0.4.0, I started seeing these exceptions:

```
-[UILabel mas_makeConstraints:]: unrecognized selector sent to instance 0x14989a80                                                                                      
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UILabel mas_makeConstraints:]: unrecognized selector sent to instance 0x14989a80'
```

No code has changed. I am importing &lt;Masonry/Masonry.h&gt; and the project builds just fine. Were there breaking changes that weren't mentioned in the README?

**Comment by ZhenguoQU** [comment]
hi,goodman i meet the same question now:
 2015-03-13 09:18:11.418 Masonry iOS Examples[14273:613] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIButton mas_updateConstraints:]: unrecognized selector sent to instance 0x7fd92a529c60' ,i can not find why it is breaking.can you help me?
