### ISSUE TITLE
why my code is different from the code in github

### ISSUE THREAD

**Issue by hxyShawn** [Masonry/Masonry#482]
![image](https://user-images.githubusercontent.com/19431668/32092494-707f21e6-babe-11e7-9411-e8bcbce92924.png)
this is masonry in my project.but I noticed the code in github has changed this mistake. I have tried pod repo update and remove masonry and install it again. But there's no difference. what can I do to update it, or it hasn't changed in cocoapd

**Comment by SingleEmail** [comment]
mee to

**Comment by xingheng** [comment]
This may be not an issue of this library but cocoapods usage.

Try `pod 'AFNetworking', :git => 'https://github.com/SnapKit/Masonry.git'` in your `Podfile`, just FYI. It's not recommended since this library is very unstable from since 1.1.0, there will be a lot of PR changes to be merged on iOS 11 related. 

***Very! Seriously!***

References: https://guides.cocoapods.org/syntax/podfile.html#pod

**Comment by GR-harry** [comment]
pod 'Masonry', :git => 'https://github.com/SnapKit/Masonry.git'

**Comment by SingleEmail** [comment]
Upstairs is right，I've solved this problem，thanks

**Comment by sclcoder** [comment]
TKS this issue

**Comment by hxyShawn** [comment]
thank you all very much I have solved my problem Sorry to reply so late
